import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { checkAndAwardAchievements } from "@/lib/achievements";
import { notifyLessonCompleted } from "@/lib/lesson-notifications";

const schema = z.object({
  score: z.number().int().min(0).max(100).optional(),
  timeSpentSecs: z.number().int().min(0).optional(),
});

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id: lessonId } = await params;
  const body = await req.json().catch(() => ({}));
  const parsed = schema.safeParse(body);
  const { score, timeSpentSecs } = parsed.success ? parsed.data : {};

  const now = new Date();
  const previousProgress = await db.userLessonProgress.findUnique({
    where: { userId_lessonId: { userId: session.user.id, lessonId } },
    select: { status: true },
  });

  // Upsert lesson progress → COMPLETED
  await db.userLessonProgress.upsert({
    where: { userId_lessonId: { userId: session.user.id, lessonId } },
    update: {
      status: "COMPLETED",
      score: score ?? null,
      timeSpentSecs: timeSpentSecs ?? 0,
      completedAt: now,
    },
    create: {
      userId: session.user.id,
      lessonId,
      status: "COMPLETED",
      score: score ?? null,
      timeSpentSecs: timeSpentSecs ?? 0,
      startedAt: now,
      completedAt: now,
    },
  });

  // Update streak
  await updateStreak(session.user.id);

  // Update unit progress
  await updateUnitProgress(session.user.id, lessonId);

  // Auto-assign homework for this lesson
  await autoAssignHomework(session.user.id, lessonId);
  await checkAndAwardAchievements(session.user.id);
  if (previousProgress?.status !== "COMPLETED") {
    await notifyLessonCompleted(session.user.id, lessonId);
  }

  return NextResponse.json({ success: true });
}

async function updateStreak(userId: string) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const streak = await db.learningStreak.findUnique({ where: { userId } });
  if (!streak) {
    await db.learningStreak.create({
      data: { userId, currentStreak: 1, longestStreak: 1, lastActiveDate: today },
    });
    return;
  }

  const lastActive = streak.lastActiveDate ? new Date(streak.lastActiveDate) : null;
  if (lastActive) lastActive.setHours(0, 0, 0, 0);

  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);

  let newStreak = streak.currentStreak;
  if (!lastActive || lastActive.getTime() < yesterday.getTime()) {
    newStreak = 1; // streak broken
  } else if (lastActive.getTime() === yesterday.getTime()) {
    newStreak += 1; // streak continues
  }
  // If lastActive === today, streak unchanged

  await db.learningStreak.update({
    where: { userId },
    data: {
      currentStreak: newStreak,
      longestStreak: Math.max(streak.longestStreak, newStreak),
      lastActiveDate: today,
    },
  });
}

async function updateUnitProgress(userId: string, lessonId: string) {
  const lesson = await db.lesson.findUnique({
    where: { id: lessonId },
    include: {
      unit: {
        include: {
          lessons: { where: { isPublished: true }, select: { id: true } },
        },
      },
    },
  });
  if (!lesson) return;

  const unitId = lesson.unitId;
  const allLessonIds = lesson.unit.lessons.map((l) => l.id);
  const completedCount = await db.userLessonProgress.count({
    where: { userId, lessonId: { in: allLessonIds }, status: "COMPLETED" },
  });

  const allDone = completedCount >= allLessonIds.length;

  await db.userUnitProgress.upsert({
    where: { userId_unitId: { userId, unitId } },
    update: {
      status: allDone ? "COMPLETED" : "IN_PROGRESS",
      completedAt: allDone ? new Date() : null,
    },
    create: {
      userId,
      unitId,
      status: allDone ? "COMPLETED" : "IN_PROGRESS",
      startedAt: new Date(),
      completedAt: allDone ? new Date() : null,
    },
  });
}

async function autoAssignHomework(userId: string, lessonId: string) {
  const homeworkList = await db.homework.findMany({
    where: { lessonId, isAutoGenerated: true, isActive: true },
  });

  for (const hw of homeworkList) {
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + hw.dueOffsetDays);
    await db.homeworkAssignment.upsert({
      where: { homeworkId_userId: { homeworkId: hw.id, userId } },
      update: {},
      create: { homeworkId: hw.id, userId, dueDate },
    });
  }
}
